---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggeffects)
library(dplyr)
library(ghibli)
library(lme4)
library(lmerTest)
library(ghibli)

```

```{r load_data, include=FALSE}

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/English.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/English_UD.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/English_auto.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/French.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/French_UD.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/French_auto.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Italian.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Italian_UD.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Italian_auto.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Japanese.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Japanese_UD.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Korean.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Korean_UD.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Turkish.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Turkish_UD.Rda")

load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Russian.Rda")
load(file="~/Documents/research/git-projects/YouDePP/data/rdata/Russian_UD.Rda")

```

```{r setup_ud_data, include=FALSE}

df.all.ud <- bind_rows(list("Japanese"=df.ud.ja, "Russian"=df.ud.ru, "Italian"=df.ud.it, "Korean"=df.ud.ko, "Turkish"=df.ud.tr, "English"=df.ud.en, "French"=df.ud.fr), .id="language") %>% mutate(sentence_uid=paste(language, sentence_id, sep='_'))

df.all.ud$sent_len_sq <- df.all.ud$total_length * df.all.ud$total_length
  
df.all.ud$baseline =  factor(df.all.ud$baseline)
df.all.ud$language =  factor(df.all.ud$language, c("English", "Italian", "French", "Russian", "Japanese", "Turkish", "Korean"))

# Observed deps for density hexagons
df.ud.observed <- df.all.ud %>% filter(baseline=="Observed")

# Sentences of length 12 (for histograms)
df.ud.12 <- df.all.ud %>% filter(total_length == 12)

# Average deps by baseline for fitted scatter plots
df.ud.avg <- df.all.ud %>% 
  group_by(language, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()

# Observed-only averages
df.ud.observed.avg <- df.ud.avg %>% filter(baseline=="Observed")

```

```{r setup_data, include=FALSE}

df.manual <-  bind_rows(list("Japanese"=df.all.ja, "Korean"=df.all.ko, "Russian"=df.all.ru, "Turkish"=df.all.tr, "Italian"=df.all.it, "French"=df.all.fr,  "English"=df.all.en), .id="language")
df.manual$language <- factor(df.manual$language, c("English", "Italian", "French", "Russian", "Japanese", "Turkish", "Korean"))

df.auto   <- bind_rows(list("Italian"=df.all.it.auto, "French"=df.all.fr.auto,  "English"=df.all.en.auto), .id="language")
df.auto$language <- factor(df.auto$language, c("French", "English", "Italian"))

df.ud.manual <- bind_rows(list("YouDePP"=(df.manual %>% select(language, baseline, sentence_id, sentence_uid, dep_length, total_length, sent_len_sq)), "UD"=df.all.ud), .id="corpus")

df.ud.all <- bind_rows(list("YouDePP"=(df.manual %>% select(language, baseline, sentence_id, sentence_uid, dep_length, total_length, sent_len_sq)),
                            "YouDePP"=(df.auto   %>% select(language, baseline, sentence_id, sentence_uid, dep_length, total_length, sent_len_sq)),
                            "UD"=df.all.ud), .id="corpus")
df.ud.manual$corpus <- factor(df.ud.manual$corpus)
df.ud.all$corpus    <- factor(df.ud.all$corpus)

df.all <- df.manual#bind_rows(list("manual"=df.manual, "auto"=df.auto), .id="subtitle_type")
df.all$language      <- factor(df.all$language, c("English", "Italian", "French", "Russian", "Japanese", "Turkish", "Korean"))
df.all$channel       <- factor(df.all$channel)
df.all$sentence_uid  <- factor(df.all$sentence_uid)
#df.all$subtitle_type <- factor(df.all$subtitle_type)

df.auto.comp <- bind_rows(list("manual"=df.manual, "auto"=df.auto), .id="subtitle_type") %>% filter(language != "Russian" & language !="Japanese" & language !="Turkish" & language !="Korean")

# Observed deps for density hexagons
df.all.observed <- df.all %>% filter(baseline=="Observed")
df.auto.comp.observed <- df.auto.comp %>% filter(baseline=="Observed")
df.ud.all.observed <- df.ud.all %>% filter(baseline=="Observed")

# Sentences of length 12 (for histograms)
df.all.12 <- df.all %>% filter(total_length == 12)

# Average deps by baseline for fitted scatter plots
df.all.avg <- df.all %>% 
  filter(channel != "FischersCorrected") %>% 
  group_by(language, baseline, total_length) %>% 
  summarize("avg_length"=mean(dep_length)) %>% 
  ungroup()

df.auto.comp.avg <- df.auto.comp %>% 
  group_by(language, subtitle_type, baseline, total_length) %>% 
  summarize("avg_length"=mean(dep_length)) %>% 
  ungroup()

df.ud.all.avg <- df.ud.all %>% 
  group_by(language, corpus, baseline, total_length) %>% 
  summarize("avg_length"=mean(dep_length)) %>% 
  ungroup()

# Average deps by channel and baseline for fitted scatter plots
df.all.avg.chan <- df.all %>% 
  group_by(language, channel, baseline, total_length) %>% 
  summarize("avg_length"=mean(dep_length)) %>% 
  ungroup()

# Observed-only averages
df.all.observed.avg <- df.all.avg %>% filter(baseline=="Observed")
df.auto.comp.observed.avg <- df.auto.comp.avg %>% filter(baseline=="Observed")
df.all.observed     <- df.all %>% filter(baseline=="Observed")

df.manual %>% filter(baseline=="Observed") %>% summarize(count=n(), avgl=mean(total_length), sd=sd(total_length))
df.ud.all %>% group_by(language, corpus) %>% filter(baseline=="Observed" & total_length <= 15) %>% summarize(count=n(), avgl=mean(total_length), sd=sd(total_length))

```

```{r quick_box_man}

df.manual <- df.manual %>% mutate(languageN = if_else(language=="Japanese", "Japanese\nn=398522", if_else(language=="Korean", "Korean\nn=46258", if_else(language=="Russian", "Russian\nn=143151", if_else(language=="Turkish", "Turkish\nn=103952", if_else(language=="English", "English\nn=16293", if_else(language=="Italian", "Italian\nn=6693", if_else(language=="French", "French\nn=11955", ""))))))), "subtitle_type"="Manual")

boxplot.manual <- ggplot(df.manual %>% filter(baseline == "Observed" & total_length <= 15), aes(x=languageN, y=total_length, color=language, fill=language)) +
  geom_boxplot(show.legend=FALSE, outlier.shape=NA, alpha=0.5)  + 
  scale_fill_manual(values=c("#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d")) + 
  scale_color_manual(values=c("#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d")) + 
  theme_bw() + 
  labs(title="", x="Language", y="Length of Utterance", color="") + 
  theme(
      text = element_text(size = 30),
      axis.ticks = element_line(colour = "grey70", size = 0.2),
      panel.grid.major = element_line(colour = "grey70", size = 0.2),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill="white", color="grey70"),
      strip.background = element_rect(fill="grey90", color="grey70")
  ) +
  facet_grid(.~subtitle_type)

ggsave("plots/distribution_manual.png", plot=boxplot.manual, device="png", dpi = 300, width=12)
boxplot.manual 

```

```{r quick_box_auto}

df.auto %>% filter(baseline == "Observed" & total_length <= 15) %>% group_by(language) %>% summarize(count = n())

df.auto.tmp <- df.auto %>% 
  mutate(languageN = if_else(language=="English", "English\nn=570369", if_else(language=="French", "French\nn=399301", if_else(language=="Italian", "Italian\nn=425788",  ""))), 
         subtitle_type="Auto-generated")

boxplot.auto <- ggplot(df.auto.tmp %>% filter(baseline == "Observed" & total_length <= 15), aes(x=languageN, y=total_length, color=language, fill=language)) +
  geom_violin(show.legend=FALSE, outlier.shape=NA, alpha=0.5)  + 
  scale_fill_manual(values=c("#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d")) + 
  scale_color_manual(values=c("#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d","#61c75d")) + 
  theme_bw() + 
  labs(title="", x="Language", y="Length of Utterance", color="") + 
  theme(
      text = element_text(size = 30),
      axis.ticks = element_line(colour = "grey70", size = 0.2),
      panel.grid.major = element_line(colour = "grey70", size = 0.2),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill="white", color="grey70"),
      strip.background = element_rect(fill="grey90", color="grey70")
  ) +
  facet_grid(.~subtitle_type)

ggsave("plots/distribution_auto.png", plot=boxplot.auto , device="png", dpi = 300, height=7, width=8)
boxplot.auto 

```

```{r total_aggregate_dependencies, include=TRUE}

all.dependencies <- ggplot(df.all.avg %>% filter(total_length <= 15), aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.observed %>% filter(channel != "FischersCorrected" & total_length <= 15), bins=50, binwidth = c(1, 5), show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, alpha=..density..), fill="black") +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values=c("#61c75d", "#3d4f8d", "#46a1d8"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    coord_cartesian(xlim=c(0,15), ylim=c(0,100)) +
    facet_wrap(.~language, ncol=4) + 
    theme_bw() + 
      theme(
          text = element_text(size = 30),
          legend.text = element_text(size = 30),
          legend.title = element_text(size = 30),
          legend.position = "bottom",
          axis.ticks = element_line(colour = "grey70", size = 0.2),
          panel.grid.major = element_line(colour = "grey70", size = 0.2),
          panel.grid.minor = element_blank()
      )

ggsave("plots/total_dependencies_all_languages.png", plot=all.dependencies, device="png", dpi = 300, width=10)
all.dependencies

```

```{r total_aggregate_dependencies_auto, include=TRUE}
                                    
all.auto.dependencies <- ggplot(df.auto.comp.avg %>% filter(total_length <= 15), aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.auto.comp.observed %>% filter(total_length <= 15), bins=50, binwidth = c(1, 5), show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, alpha=..density..), fill="black") +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values=c("#61c75d", "#3d4f8d", "#46a1d8"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    coord_cartesian(xlim=c(0,15), ylim=c(0,100)) +
    facet_wrap(facets=c(.~language, .~subtitle_type), ncol=2) + 
    theme_bw() + 
      theme(
          text = element_text(size = 20),
          legend.text = element_text(size = 20),
          legend.title = element_text(size = 20),
          legend.position = "bottom",
          axis.ticks = element_line(colour = "grey70", size = 0.2),
          panel.grid.major = element_line(colour = "grey70", size = 0.2),
          panel.grid.minor = element_blank()
      )

ggsave("plots/total_dependencies_all_languages_auto.png", plot=all.auto.dependencies, device="png", dpi = 300, width=6)
all.auto.dependencies

```

```{r total_aggregate_dependencies_ud, include=TRUE}

all.dependencies.ud <- ggplot(df.ud.avg %>% filter(total_length <= 15), aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.ud.observed %>% filter(total_length <= 15), bins=50, binwidth = c(1, 5), show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, alpha=..density..), fill="black") +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values=c("#61c75d", "#3d4f8d", "#46a1d8"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    coord_cartesian(xlim=c(0,15), ylim=c(0,100)) +
    facet_wrap(.~language, ncol=4) + 
    theme_bw() + 
      theme(
          text = element_text(size = 30),
          legend.text = element_text(size = 30),
          legend.title = element_text(size = 30),
          legend.position = "bottom",
          axis.ticks = element_line(colour = "grey70", size = 0.2),
          panel.grid.major = element_line(colour = "grey70", size = 0.2),
          panel.grid.minor = element_blank()
      )

ggsave("plots/total_dependencies_ud.png", plot=all.dependencies.ud, device="png", dpi = 300, width=10)
all.dependencies.ud

```

```{r}

df.auto.lm <- df.auto.comp %>% filter(baseline != "Optimal" & total_length < 15) %>%
  select(language, subtitle_type, baseline, sentence_uid, dep_length, total_length, sent_len_sq)
df.auto.lm$subtitle_type <- factor(df.auto.lm$subtitle_type)

```

```{r}

print("ITALIAN AUTO")

lm.it.auto <- lmer(dep_length ~ sent_len_sq * baseline * subtitle_type + (1 | sentence_uid), data = (df.auto.lm %>% filter(language == "Italian")), control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)))

lm.it.auto.reduced <- lmer(dep_length ~ sent_len_sq + baseline + subtitle_type + subtitle_type:sent_len_sq + baseline:sent_len_sq + baseline:subtitle_type + (1| sentence_uid), data = (df.auto.lm %>% filter(language == "Italian")), control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)))

anova(lm.it.auto, lm.it.auto.reduced)
summary(lm.it.auto)

```

```{r}

print("FRENCH AUTO")

lm.fr.auto <- lmer(dep_length ~ sent_len_sq * baseline * subtitle_type + (1 | sentence_uid), data = (df.auto.lm %>% filter(language == "French")))
lm.fr.auto.reduced <- lmer(dep_length ~ sent_len_sq + baseline + subtitle_type + subtitle_type:sent_len_sq + baseline:sent_len_sq + baseline:subtitle_type + (1| sentence_uid), data = (df.auto.lm %>% filter(language == "French")))

anova(lm.fr.auto, lm.fr.auto.reduced)
summary(lm.fr.auto)

```

```{r}

auto.direct.g <- ggplot(df.auto.observed.lm, aes(y=dep_length, x=total_length, color=subtitle_type, group=subtitle_type)) + 
    geom_smooth(aes(group=subtitle_type), se = TRUE, method = "lm", formula = y ~ x^2) + 
    scale_color_manual(values=c("#61c75d", "#46a1d8")) + 
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    facet_wrap(.~language) +
    theme_bw() + 
      theme(
          text = element_text(size = 30),
          legend.text = element_text(size = 30),
          legend.title = element_text(size = 30),
          legend.position = "bottom",
          axis.ticks = element_line(colour = "grey70", size = 0.2),
          panel.grid.major = element_line(colour = "grey70", size = 0.2),
          panel.grid.minor = element_blank()
      )

#ggsave("plots/total_dependencies_ud.png", plot=all.dependencies.ud, device="png", dpi = 300, width=10)
auto.direct.g 

```

```{r}

print("ENGLISH AUTO")

lm.en.auto <- lmer(dep_length ~ sent_len_sq * baseline * subtitle_type + (1 | sentence_uid), data = (df.auto.lm %>% filter(language == "English")))
lm.en.auto.reduced <- lmer(dep_length ~ sent_len_sq + baseline + subtitle_type + subtitle_type:sent_len_sq + baseline:sent_len_sq + baseline:subtitle_type + (1| sentence_uid), data = (df.auto.lm %>% filter(language == "English")))

anova(lm.en.auto, lm.en.auto.reduced)
summary(lm.en.auto)

```

```{r}

print("ITALIAN MODEL")
lm.it.ud <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=(df.ud.manual.lm %>% filter(language == "Italian")))
lm.it.ud.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=(df.ud.manual.lm %>% filter(language == "Italian")))

anova(lm.it.ud.reduced, lm.it.ud)
summary(lm.it.ud)

```

```{r}

df.ud.manual.lm <- df.ud.manual %>% filter(total_length <= 15 & (baseline=="Observed" | baseline=="Random")) %>% select(language, corpus, baseline, sentence_uid, dep_length, total_length, sent_len_sq)

df.ud.all.lm <- df.ud.all %>% filter(total_length <= 15 & (baseline=="Observed" | baseline=="Random")) %>% select(language, corpus, baseline, sentence_uid, dep_length, total_length, sent_len_sq)

df.ud.manual.lm$baseline <- factor(df.ud.manual.lm$baseline, c("Random", "Observed"))
df.ud.manual.lm %>% group_by(corpus, language, baseline) %>% summarize(count=n())

df.ud.all.lm$baseline <- factor(df.ud.all.lm$baseline, c("Random", "Observed"))
df.ud.all.lm %>% group_by(corpus, language, baseline) %>% summarize(count=n())

```

```{r}

print("ITALIAN MODEL ALL")

df.lm.it.all <- df.ud.all.lm %>% filter(language == "Italian")
lm.it.ud.all <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.it.all)
lm.it.ud.all.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.it.all)

anova(lm.it.ud.all.reduced, lm.it.ud.all)
summary(lm.it.ud.all)

df.lm.it.all$predicted_length <- predict(lm.it.ud.all)
df.lm.it.all.avg <- df.lm.it.all %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```


# French
```{r}

print("FRENCH MODEL")

df.fr.lm.man <- df.ud.manual.lm %>% filter(language == "French")
df.ud.manual.lm %>% group_by(baseline, corpus) %>% summarize(count=n())

lm.fr.ud.man <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.fr.lm.man)
lm.fr.ud.man.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.fr.lm.man)

anova(lm.fr.ud.man.reduced, lm.fr.ud.man)
summary(lm.fr.ud.man)

```

```{r}

print("FRENCH MODEL ALL")

df.lm.fr.all <- df.ud.all.lm %>% filter(language == "French")
df.ud.all.lm %>% group_by(baseline, corpus) %>% summarize(count=n())

lm.fr.ud.all <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.fr.all)
lm.fr.ud.all.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.fr.all)

anova(lm.fr.ud.all.reduced, lm.fr.ud.all)
summary(lm.fr.ud.all)

df.lm.fr.all$predicted_length <- predict(lm.fr.ud.all)
df.lm.fr.all.avg <- df.lm.fr.all %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```

# English

```{r}
print("ENGLISH MODEL")
lm.en.ud.man <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=(df.ud.manual.lm %>% filter(language == "English")))
lm.en.ud.man.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=(df.ud.manual.lm %>% filter(language == "English")))

anova(lm.en.ud.man.reduced, lm.en.ud.man)
summary(lm.en.ud.man)
```


```{r}

print("ENGLISH MODEL ALL")
df.lm.en.all <- df.ud.all.lm %>% filter(language == "English")

lm.en.ud.all <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.en.all)
lm.en.ud.all.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.en.all)

anova(lm.en.ud.all.reduced, lm.en.ud.all)
summary(lm.en.ud.all)

df.lm.en.all$predicted_length <- predict(lm.en.ud.all)
df.lm.en.all.avg <- df.lm.en.all %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```

# Japanese
```{r}

print("JAPANESE MODEL")
df.lm.ja <- df.ud.manual.lm %>% filter(language == "Japanese")

lm.ja.ud <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.ja)
lm.ja.ud.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.ja)

anova(lm.ja.ud.reduced, lm.ja.ud)
summary(lm.ja.ud)

df.lm.ja$predicted_length <- predict(lm.ja.ud)
df.lm.ja.avg <- df.lm.ja %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```

# Korean
```{r}

df.lm.ko <- df.ud.manual.lm %>% filter(language == "Korean")

lm.ko.ud <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.ko)
lm.ko.ud.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.ko)

anova(lm.ko.ud.reduced, lm.ko.ud)
summary(lm.ko.ud)

df.lm.ko$predicted_length <- predict(lm.ko.ud)
df.lm.ko.avg <- df.lm.ko %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```

# Turkish
```{r}

print("TURKISH MODEL")
df.lm.tr <- df.ud.manual.lm %>% filter(language == "Turkish")

lm.tr.ud <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.tr)
lm.tr.ud.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.tr)

anova(lm.tr.ud.reduced, lm.tr.ud)
summary(lm.tr.ud)

df.lm.tr$predicted_length <- predict(lm.tr.ud)
df.lm.tr.avg <- df.lm.tr %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```

# Russian

```{r}

print("RUSSIAN MODEL")
df.lm.ru <- df.ud.manual.lm %>% filter(language == "Russian")

lm.ru.ud <- lmer(dep_length ~ sent_len_sq * baseline * corpus + (1 | sentence_uid), data=df.lm.ru)
lm.ru.ud.reduced <- lmer(dep_length ~ sent_len_sq + baseline + corpus + corpus:sent_len_sq + baseline:sent_len_sq + baseline:corpus + (1| sentence_uid), data=df.lm.ru)

anova(lm.ru.ud.reduced, lm.ru.ud)
summary(lm.ru.ud)

df.lm.ru$predicted_length <- predict(lm.ru.ud)
df.lm.ru.avg <- df.lm.ru %>% group_by(corpus, baseline, total_length) %>% summarize(avg_dep=mean(dep_length), avg_predicted_dep=mean(predicted_length)) %>% ungroup()

```



```{r}

all.fits.avg <- bind_rows(list("English"=df.lm.en.all.avg, "French"=df.lm.fr.all.avg, "Italian"=df.lm.it.all.avg, "Russian"=df.lm.ru.avg, "Japanese"=df.lm.ja.avg, "Turkish"=df.lm.tr.avg, "Korean"=df.lm.ko.avg), .id="language")

all.fits.avg$language <- factor(all.fits.avg$language, c("French", "Russian", "Italian", "English", "Japanese", "Turkish", "Korean"))

model.g <- ggplot(all.fits.avg, aes(x=total_length, y=avg_dep, group=interaction(baseline, corpus), color=baseline, shape=corpus)) + 
  geom_line(aes(y=avg_predicted_dep, linetype=corpus), size=0.8) +
  scale_color_manual(values=c("#61c75d", "#46a1d8")) + 
  facet_wrap(.~language, ncol=4) +
  theme_bw() +
  labs(title="", x="Sentence Length", y="Total Dependency Length", color="Baseline", linetype="Corpus") + 
  #theme(legend.position="bottom") +
  theme_bw() + 
    theme(
        text = element_text(size = 20),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.ticks = element_line(colour = "grey70", size = 0.2),
        panel.grid.major = element_line(colour = "grey70", size = 0.2),
        panel.grid.minor = element_blank()
    )

ggsave("plots/model_fits.png", plot=model.g, device="png", dpi = 300, width=10)
model.g

```


```{r}

df.ud.all.avg$corpus <- factor(df.ud.all.avg$corpus, c("YouDePP", "UD"))
df.ud.all.avg$language <- factor(df.ud.all.avg$language, c("French", "Russian", "Italian", "English", "Japanese", "Turkish", "Korean"))

corpora.g2 <- ggplot((df.ud.all.avg %>% filter(total_length <= 15 & language != "Japanese" & language != "Korean" & language != "Turkish")), aes(x=total_length, y=avg_length, color=baseline)) + 
  geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
  stat_bin_hex(data=df.ud.all.observed %>% filter(total_length <= 15 & language != "Japanese" & language != "Korean" & language != "Turkish"), bins=50, binwidth = c(1, 5), show.legend=FALSE, inherit.aes=FALSE, aes(y=dep_length, x=total_length, alpha=..density..), fill="black") +
  scale_color_manual(values=c("#61c75d", "#3d4f8d", "#46a1d8"), labels=c("Random", "Optimal", "Observed")) + 
  facet_grid(language ~ corpus) +
  theme_bw() +
  labs(title="", x="Sentence Length", y="Total Dependency Length", color="Baseline", linetype="Corpus") + 
  #theme(legend.position="bottom") +
  theme_bw() + 
    theme(
        text = element_text(size = 20),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.ticks = element_line(colour = "grey70", size = 0.2),
        panel.grid.major = element_line(colour = "grey70", size = 0.2),
        panel.grid.minor = element_blank()
    )

ggsave("plots/ud_youdepp_comparison_1.png", plot=corpora.g2, device="png", dpi = 300, height=8.95, width=7)
corpora.g2

```


```{r}
corpora.g3 <- ggplot((df.ud.all.avg %>% filter(total_length <= 15 & (language == "Japanese" | language == "Korean" | language == "Turkish"))), aes(x=total_length, y=avg_length, color=baseline)) + 
  geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
  stat_bin_hex(data=df.ud.all.observed %>% filter(total_length <= 15 & (language == "Japanese" | language == "Korean" | language == "Turkish")), bins=50, binwidth = c(1, 5), show.legend=FALSE, inherit.aes=FALSE, aes(y=dep_length, x=total_length, alpha=..density..), fill="black") +
  scale_color_manual(values=c("#61c75d", "#3d4f8d", "#46a1d8"), labels=c("Random", "Optimal", "Observed")) + 
  facet_grid(language ~ corpus) +
  theme_bw() +
  labs(title="", x="Sentence Length", y="Total Dependency Length", color="Baseline", linetype="Corpus") + 
  theme_bw() + 
    theme(
        text = element_text(size = 20),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        legend.position ="bottom",
        axis.ticks = element_line(colour = "grey70", size = 0.2),
        panel.grid.major = element_line(colour = "grey70", size = 0.2),
        panel.grid.minor = element_blank()
    )

ggsave("plots/ud_youdepp_comparison_2.png", plot=corpora.g3, device="png", dpi = 300, height=7.6, width=5.5)
corpora.g3
```