---
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
    fig_caption: yes
  html_document: default
always_allow_html: yes
geometry: margin=1in
documentclass: article
header-includes:
  - \setlength{\parindent}{2em}
  - \setlength{\parskip}{0em}
  - \usepackage{setspace, booktabs}
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(gridExtra)
library(dplyr)
library(ghibli)
library(lme4)
library(gamm4)
library(mgcv)
library(itsadug)

```

```{r load_data, include=FALSE}

source("~/Documents/research/git-projects/YouDePP/data/plots/load_japanese.R")
source("~/Documents/research/git-projects/YouDePP/data/plots/load_russian.R")

df.all.ja <- loadJapanese()
df.all.ru <- loadRussian()

```


```{r setup_data, include=FALSE}

# Observed deps for density hexagons
df.all.ja.observed <- df.all.ja %>% filter(baseline=="Observed")
df.all.ru.observed <- df.all.ru %>% filter(baseline=="Observed")

# Sentences of length 12 (for histograms)
df.all.ja.12 <- df.all.ja %>% filter(total_length == 12)
df.all.ru.12 <- df.all.ru %>% filter(total_length == 12)

# Average deps by baseline for fitted scatter plots
df.all.ja.avg <- df.all.ja %>% 
  filter(channel != "FischersCorrected") %>% 
  group_by(baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.ru.avg <- df.all.ru %>% 
  group_by(baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()

# Average deps by channel and baseline for fitted scatter plots
df.all.ja.avg.chan <- df.all.ja %>% 
  group_by(channel, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.ru.avg.chan <- df.all.ru %>% 
  group_by(channel, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()

# Observed-only averages
df.all.ja.observed.avg <- df.all.ja.avg %>% filter(baseline=="Observed")
df.all.ru.observed.avg <- df.all.ru.avg %>% filter(baseline=="Observed")

# Re-do factors
df.all <- bind_rows(list("Japanese"=df.all.ja, "Russian"=df.all.ru), .id="language")
df.all$language     <- factor(df.all$language)
df.all$channel      <- factor(df.all$channel)
df.all$sentence_uid <- factor(df.all$sentence_uid)

```


```{r total_dependencies_japanese_bychannel, include=TRUE, echo=FALSE}

dep.by.channel.ja <- ggplot(df.all.ja.avg.chan, aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ja.observed, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Total Dependency Lengths by Sentence Length per Channel, Japanese", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    facet_wrap(.~channel) + theme_minimal()

ggsave("total_dependencies_channel_ja.png", plot=dep.by.channel.ja, device="png", dpi = 300)
dep.by.channel.ja

```

```{r total_dependencies_russian_bychannel, include=TRUE, echo=FALSE}

dep.by.channel.ru <- ggplot(df.all.ru.avg.chan, aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ru.observed %>% filter(dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Total Dependency Lengths by Sentence Length per Channel, Russian", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal()
    facet_wrap(.~channel)

ggsave("total_dependencies_channel_ru.png", plot=dep.by.channel.ru, device="png", dpi = 300)
dep.by.channel.ru

```

```{r average_dependencies_japanese_bychannel, include=TRUE, echo=FALSE}

avg.dep.by.channel.ja <- ggplot(df.all.ja, aes(y=dep_length/total_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ja.observed, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length/total_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length per Channel, Japanese", x="Sentence Length", y="Average Dependency Length", color="") +
    theme(legend.position="bottom") + theme_minimal() +
    facet_wrap(.~channel)

ggsave("average_dependencies_channel_ja.png", plot=avg.dep.by.channel.ja, device="png", dpi = 300)
avg.dep.by.channel.ja

```

```{r average_dependencies_russian_bychannel, include=TRUE, echo=FALSE}

avg.dep.by.channel.ru <- ggplot(df.all.ru, aes(y=dep_length/total_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ru.observed %>% filter(dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length/total_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length per Channel, Russian", x="Sentence Length", y="Average Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal() +
    facet_wrap(.~channel)

ggsave("average_dependencies_channel_ru.png", plot=avg.dep.by.channel.ru, device="png", dpi = 300)
avg.dep.by.channel.ru

```

```{r total_aggregate_dependencies_ja, include=TRUE}

# NOTE: Uncorrected data only!
all.dependencies.ja <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.observed %>% filter(channel != "FischersCorrected"), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Total Depedency Length by Sentence Length, Japanese", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal()

ggsave("total_dependencies_aggregate_ja.png", plot=all.dependencies.ja, device="png", dpi = 300)
all.dependencies.ja

```

```{r total_aggregate_dependencies_ru, include=TRUE}

all.dependencies.ru <- ggplot(df.all.ru.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ru.observed %>% filter(dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) +  
    labs(title="Total Average Depedency Length by Sentence Length, Russian", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal()

ggsave("total_dependencies_aggregate_ru.png", plot=all.dependencies.ru, device="png", dpi = 300)
all.dependencies.ru

```

```{r quantile_plots, include=TRUE, echo=FALSE}

all.dependencies.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=avg_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_quantile(aes(alpha = ..quantile..)) +
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed")) +
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom")
all.dependencies.g

```

```{r aggregate_hist_ja, include=TRUE, echo=FALSE}

hist.12.all.ja <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths For Sentences of Length 12, Japanese") + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    theme(legend.position="bottom")

ggsave("histogram_dependencies_aggregate_ja.png", plot=hist.12.all.ja, device="png", dpi = 300)
hist.12.all.ja

```

```{r hist_bychannel_ja, include=TRUE, echo=FALSE}

hist.12.channel.ja <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    facet_wrap(.~channel) + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths by Channel For Sentences of Length 12, Japanese") +
  theme(legend.position="bottom")

ggsave("histogram_dependencies_channel_ja.png", plot=hist.12.channel.ja, device="png", dpi = 300)
hist.12.channel.ja

```

```{r aggregate_hist_ru, include=TRUE, echo=FALSE}

hist.12.all.ru <- ggplot(data=df.all.ru.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths For Sentences of Length 12, Russian") + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    theme(legend.position="bottom")

ggsave("histogram_dependencies_aggregate_ru.png", plot=hist.12.all.ru, device="png", dpi = 300)
hist.12.all.ru

```

```{r hist_bychannel_ru, include=TRUE, echo=FALSE}

hist.12.channel.ru <- ggplot(data=df.all.ru.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    facet_wrap(.~channel) + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths by Channel For Sentences of Length 12, Japanese") +
  theme(legend.position="bottom")

ggsave("histogram_dependencies_channel_ru.png", plot=hist.12.channel.ru, device="png", dpi = 300)
hist.12.channel.ru

```

```{r}
all.dependencies.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.observed.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_smooth(aes(group=baseline), se = FALSE, method = "gam", formula = y ~ s(log(x)), show.legend = FALSE) + 
    labs(title="", x="", y="", color="") + 
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed"))
  
# Plot by channel
dep.by.channel.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ja.observed.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_smooth(aes(group=baseline), se = FALSE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    labs(title="", x="", y="", color="") + 
    theme(legend.position="top") +
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed")) +
    facet_wrap(.~channel)
  
g <- grid.arrange(all.dependencies.g, dep.by.channel.g, ncol=2, left="Total Dependency Length", bottom="Sentence Length", widths=unit(c(3,6), c("in", "in")))

```

```{r}
hist.12.channel.g <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity", show.legend=FALSE) + 
    facet_wrap(.~channel) + 
    labs(x="", y="", title="",color="", fill="") + 
    theme(legend.position="top") +
    scale_fill_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], 
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill"))

hist.12.all.g <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity", show.legend=FALSE) + 
    labs(x="", y="", title="",color="", fill="") + 
    theme(legend.position="bottom") +
    scale_fill_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], 
                      labels = c("Rand", "Opt", "Obs"), aesthetics = c("colour", "fill"))
g2 <- grid.arrange(hist.12.all.g, hist.12.channel.g, ncol=2, left="Frequency", bottom="Total Dependency Length", widths=unit(c(3,6), c("in", "in")))
```

```{r}
require(grid)
require(gridExtra)
grid.draw(g)
ggsave("all_dependencies_with_chan_plot.png", plot=g, width=10, height=5, device="png", dpi=300)

grid.draw(g2)
ggsave("hist_12_with_chan_plot.png", plot=g2, width=10,  height=5, device="png", dpi=300)

```

```{r linear_model, include=TRUE}
temp <- df.all.ja %>% filter(channel == 1 & (baseline == "Observed" | baseline == "Random"))
#temp$o <- as.factor(temp$o)
#temp$r <- as.factor(temp$r)

# sent  l       y   l^2   m   r
# 1     10      30  100   0   0 
# 1     10      20  100   1   0 
# 1     10      40  100   0   1 

# Structural model: y_i = β_0 + S_0 + β_1l_2^s + (β_2 + S_2)r_i + β_3r_il_2^s + e_i
# β_0 = slope
# β_1, β_2,  β_3 = fixed effects
# S_0, S_2 = random effects (intercept, slope) by sentence
# r_i = ind. var. for random
# m_i = ind. var. for optimal

# Compute models with and without the interaction term, with random = 1
dependency.model.b3 <- lmer(dep_length ~ sent_len_sq + r:sent_len_sq + r + (1+r||(video_id:sentence_id)), data=temp)
#dependency.model.nob3 <- lmer(dep_length ~ sent_len_sq + r + (1+r||(video_id:sentence_id)), data=temp)

# Random = 0, obs = 1
#dependency.model.b3 <- lmer(dep_length ~ sent_len_sq + o:sent_len_sq + o + (1+o||(video_id:sentence_id)), data=temp)
```

```{r model_summaries, include=TRUE}
# Summarize models
#summary(dependency.model.b3)
summary(dependency.obsmodel.b3)
#summary(dependency.model.nob3)
```

```{r}
library(ggeffects)
df.ja.predicted <- ggpredict(dependency.model.b3, terms = c("sent_len_sq", "r"))
df.ja.predicted
ggplot(df.ja.predicted, aes(x=sqrt(x), y=predicted, group=group, color=group)) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)
```

```{r, include=TRUE}
# Compare models
anova(dependency.model.b3,dependency.model.nob3)
```