---
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: yes
    fig_caption: yes
  html_document: default
always_allow_html: yes
geometry: margin=1in
documentclass: article
header-includes:
  - \setlength{\parindent}{2em}
  - \setlength{\parskip}{0em}
  - \usepackage{setspace, booktabs}
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggeffects)
library(dplyr)
library(ghibli)
library(lme4)
library(gamm4)
library(mgcv)
library(itsadug)

```

```{r load_data, include=FALSE}

source("~/Documents/research/git-projects/YouDePP/scripts/rscripts/load_japanese.R")
source("~/Documents/research/git-projects/YouDePP/scripts/rscripts/load_russian.R")
source("~/Documents/research/git-projects/YouDePP/scripts/rscripts/load_turkish.R")

df.all.ja <- loadJapanese()
df.all.ru <- loadRussian()
df.all.tr <- loadTurkish()

```


```{r setup_data, include=FALSE}

df.all.ja <- df.all.ja %>% filter(total_length <= 40)
df.all.ru <- df.all.ru %>% filter(total_length <= 40)
df.all.tr <- df.all.tr %>% filter(total_length <= 40)

# Observed deps for density hexagons
df.all.ja.observed <- df.all.ja %>% filter(baseline=="Observed")
df.all.ru.observed <- df.all.ru %>% filter(baseline=="Observed")
df.all.tr.observed <- df.all.tr %>% filter(baseline=="Observed")

# Sentences of length 12 (for histograms)
df.all.ja.12 <- df.all.ja %>% filter(total_length == 12)
df.all.ru.12 <- df.all.ru %>% filter(total_length == 12)
df.all.tr.12 <- df.all.tr %>% filter(total_length == 12)

# Average deps by baseline for fitted scatter plots
df.all.ja.avg <- df.all.ja %>% 
  filter(channel != "FischersCorrected") %>% 
  group_by(baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.ru.avg <- df.all.ru %>% 
  group_by(baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.tr.avg <- df.all.tr %>% 
  group_by(baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()

# Average deps by channel and baseline for fitted scatter plots
df.all.ja.avg.chan <- df.all.ja %>% 
  group_by(channel, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.ru.avg.chan <- df.all.ru %>% 
  group_by(channel, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()
df.all.tr.avg.chan <- df.all.tr %>% 
  group_by(channel, baseline, total_length) %>% summarize("avg_length"=mean(dep_length)) %>% ungroup()

# Observed-only averages
df.all.ja.observed.avg <- df.all.ja.avg %>% filter(baseline=="Observed")
df.all.ru.observed.avg <- df.all.ru.avg %>% filter(baseline=="Observed")
df.all.tr.observed.avg <- df.all.tr.avg %>% filter(baseline=="Observed")

# Re-do factors
df.all <- bind_rows(list("Japanese"=df.all.ja, "Russian"=df.all.ru, "Turkish"=df.all.tr), .id="language")
df.all$language     <- factor(df.all$language)
df.all$channel      <- factor(df.all$channel)
df.all$sentence_uid <- factor(df.all$sentence_uid)

df.all.observed <- df.all %>% filter(baseline=="Observed")
  
df.all.avg <- bind_rows(list("Japanese"=df.all.ja.avg, "Russian"=df.all.ru.avg), .id="language")
df.all.avg$language     <- factor(df.all.avg$language)
#df.all.avg$channel      <- factor(df.all.avg$channel)
#df.all.avg$sentence_uid <- factor(df.all.avg$sentence_uid)

```


```{r total_dependencies_japanese_bychannel, include=TRUE, echo=FALSE}

dep.by.channel.ja <- ggplot(df.all.ja.avg.chan %>% filter(channel != "FischersCorrected"), aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=(df.all.ja.observed %>% filter(channel != "FischersCorrected")), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    scale_color_manual(values = c("#5B675D", "#76cc41", "#00b3e7"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="", y="", color="") + 
    theme(legend.position="bottom") +
    facet_wrap(.~channel, ncol=3) +
    scale_x_continuous(trans = 'log2') +
    scale_y_continuous(trans = 'log2') +
    #coord_cartesian(ylim=c(0,300)) + 
    theme(text = element_text(size = 30))
    #scale_y_continuous(breaks=c(0,100,200,300))


ggsave("NEW_total_dependencies_channel_ja.png", plot=dep.by.channel.ja, device="png", dpi = 300, width=10)
dep.by.channel.ja

```

```{r total_dependencies_turkish_bychannel, include=TRUE, echo=FALSE}

dep.by.channel.tr <- ggplot(df.all.tr.avg.chan, aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=(df.all.tr.observed %>% filter(channel != "FischersCorrected")), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    scale_color_manual(values = c("#5B675D", "#76cc41", "#00b3e7"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="", y="", color="") + 
    scale_x_continuous(trans = 'log2') +
    scale_y_continuous(trans = 'log2') +
    theme(legend.position="bottom") +
    facet_wrap(.~channel, ncol=3) +
    #coord_cartesian(ylim=c(0,300)) + 
    theme(text = element_text(size = 30))
    #scale_y_continuous(breaks=c(0,100,200,300))


ggsave("NEW_total_dependencies_channel_tr.png", plot=dep.by.channel.tr, device="png", dpi = 300, width=10)
dep.by.channel.tr

```

```{r total_dependencies_japanese_corrected, include=TRUE, echo=FALSE}
                              
dep.corrected.comp.ja <- ggplot(df.all.ja.avg.chan %>% filter((channel == "FischersCorrected" | channel == "FischersAuto")), aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=(df.all.ja.observed %>% filter((channel == "FischersCorrected" | channel == "FischersAuto"))), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    scale_color_manual(values = c("#5B675D", "#76cc41", "#00b3e7"), labels=c("Random", "Optimal", "Observed")) +  
    labs(title="", x="", y="", color="") + 
    theme(legend.position="bottom") +
    facet_wrap(.~channel) +
    coord_cartesian(ylim=c(0,300)) + 
    theme(text = element_text(size = 40)) +
    scale_y_continuous(breaks=c(0,100,200,300))

ggsave("NEW_total_dependencies_corrected_comp_ja.png", plot=dep.corrected.comp.ja, device="png", dpi = 300, width=12)
dep.corrected.comp.ja



```

```{r total_dependencies_russian_bychannel, include=TRUE, echo=FALSE}

dep.by.channel.ru <- ggplot(df.all.ru.avg.chan %>% filter(total_length < 20), aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ru.observed %>% filter(total_length < 20), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    scale_color_manual(values = c("#5B675D", "#76cc41", "#00b3e7"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="", y="", color="") + 
    theme(legend.position="bottom") +
    facet_wrap(.~channel, ncol=4) +
    scale_x_continuous(trans = 'log2') +
    scale_y_continuous(trans = 'log2') +
    #coord_cartesian(ylim=c(0,300)) + 
    theme(text = element_text(size = 25))
    #scale_y_continuous(breaks=c(0,100,200,300))

ggsave("NEW_total_dependencies_channel_ru.png", plot=dep.by.channel.ru, device="png", dpi = 300, width=12)
dep.by.channel.ru

```

```{r average_dependencies_japanese_bychannel, include=TRUE, echo=FALSE}

avg.dep.by.channel.ja <- ggplot(df.all.ja.avg.chan %>% filter(channel != "FischersCorrected"), aes(y=avg_length/total_length, x=total_length, color=baseline, group=channel)) + 
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length per Channel, Japanese", x="Sentence Length", y="Average Dependency Length", color="") +
    theme(legend.position="bottom") + theme_minimal() +
    coord_cartesian(ylim=c(0,7)) +
    facet_wrap(.~channel)

ggsave("NEW_average_dependencies_channel_ja.png", plot=avg.dep.by.channel.ja, device="png", dpi = 300)
avg.dep.by.channel.ja

```

```{r average_dependencies_russian_bychannel, include=TRUE, echo=FALSE}

avg.dep.by.channel.ru <- ggplot(df.all.ru.avg.chan, aes(y=avg_length/total_length, x=total_length, color=baseline, group=channel)) + 
    #stat_bin_hex(data=df.all.ru.observed %>% filter(dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
    #             aes(y=dep_length/total_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length per Channel, Russian", x="Sentence Length", y="Average Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal() +
    coord_cartesian(ylim=c(0,7)) +
    facet_wrap(.~channel)

ggsave("NEW_average_dependencies_channel_ru.png", plot=avg.dep.by.channel.ru, device="png", dpi = 300)
avg.dep.by.channel.ru

```

```{r total_aggregate_dependencies_ja, include=TRUE}

# NOTE: Uncorrected data only!
all.dependencies.ja <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.observed %>% filter(channel != "FischersCorrected"), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") +
    coord_cartesian(ylim=c(0,250)) +
    annotate(geom="text", x=0.5, y=250, label="m_rand = 0.197", hjust = 0) +
    annotate(geom="text", x=0.5, y=230, label="m_obs  = 0.124", hjust = 0) +
    annotate(geom="text", x=0.5, y=210, label="m_opt  = 0.092", hjust = 0)

ggsave("NEW_total_dependencies_aggregate_ja.png", plot=all.dependencies.ja, device="png", dpi = 300)
all.dependencies.ja

```

```{r total_aggregate_dependencies_ru, include=TRUE}

all.dependencies.ru <- ggplot(df.all.ru.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ru.observed %>% filter(dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) +  
    labs(title="Total Depedency Length by Sentence Length, Russian", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal() + 
    coord_cartesian(ylim=c(0,250)) +
    annotate(geom="text", x=0.5, y=250, label="m_rand = 0.162", hjust = 0) +
    annotate(geom="text", x=0.5, y=230, label="m_obs  = 0.107", hjust = 0) +
    annotate(geom="text", x=0.5, y=210, label="m_opt   = 0.072", hjust = 0)

ggsave("NEW_total_dependencies_aggregate_ru.png", plot=all.dependencies.ru, device="png", dpi = 300)
all.dependencies.ru

```
```{r total_aggregate_dependencies_tr, include=TRUE}

# NOTE: Uncorrected data only!
all.dependencies.tr <- ggplot(df.all.tr.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.tr.observed %>% filter(channel != "FischersCorrected"), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="", x="Sentence Length", y="Average Total Dependency Length", color="") + 
    theme(legend.position="bottom")

ggsave("NEW_total_dependencies_aggregate_tr.png", plot=all.dependencies.tr, device="png", dpi = 300)
all.dependencies.tr

```

```{r total_aggregate_dependencies}

df.all.avg$language <- relevel(df.all.avg$language, "Russian")
all.dependencies.g <- ggplot(df.all.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline, show.legend=FALSE)) + 
    stat_bin_hex(data=df.all.observed %>% filter(channel != "FischersCorrected", dep_length < 300), bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    scale_color_manual(values = c("#5B675D", "#76cc41", "#00b3e7"), labels=c("Random", "Optimal", "Observed")) +  
    labs(title="", x="", y="", color="") + 
    theme(legend.position="bottom") +
    coord_cartesian(ylim=c(0,300)) +
    theme(text = element_text(size = 65)) +
    facet_wrap(.~language) + 
    scale_y_continuous(breaks=c(0,100,200,300)) + 
    theme(legend.position="right")

ggsave("NEW_total_dependencies_aggregate.png", plot=all.dependencies.g, device="png", dpi = 300, width=15, height=8)
all.dependencies.g
```

```{r average_dependencies_japanese_aggregate, include=TRUE, echo=FALSE}

avg.dep.all.ja <- ggplot(df.all.ja.avg, aes(y=avg_length/total_length, x=total_length, color=baseline)) + 
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length, Japanese", x="Sentence Length", y="Average Dependency Length", color="") + 
    coord_cartesian(ylim=c(0,7)) +
    theme(legend.position="bottom") + theme_minimal()

ggsave("NEW_average_dependencies_aggregate_ja.png", plot=avg.dep.all.ja, device="png", dpi = 300)
avg.dep.all.ja

```

```{r average_dependencies_russian_aggregate, include=TRUE, echo=FALSE}

avg.dep.all.ru <- ggplot(df.all.ru.avg, aes(y=avg_length/total_length, x=total_length, color=baseline)) + 
    scale_fill_gradientn(colours=c("#f8f9f5","#000000")) +
    geom_smooth(aes(group=baseline), se = TRUE, method = "gam", formula = y ~ s(log(x))) + 
    scale_color_manual(values = c("#5B675D", "#60C7AA", "#A1C439"), labels=c("Random", "Optimal", "Observed")) + 
    labs(title="Average Dependency Length by Sentence Length, Russian", x="Sentence Length", y="Average Dependency Length", color="") + 
    theme(legend.position="bottom") + theme_minimal() +
    coord_cartesian(ylim=c(0,7))

ggsave("NEW_average_dependencies_aggregate_ru.png", plot=avg.dep.all.ru, device="png", dpi = 300)
avg.dep.all.ru

```

```{r quantile_plots, include=TRUE, echo=FALSE}

all.dependencies.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=avg_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_quantile(aes(alpha = ..quantile..)) +
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed")) +
    labs(title="", x="Sentence Length", y="Total Dependency Length", color="") + 
    theme(legend.position="bottom")
all.dependencies.g

```

```{r aggregate_hist_ja, include=TRUE, echo=FALSE}

hist.12.all.ja <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths For Sentences of Length 12, Japanese") + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    theme(legend.position="bottom")

ggsave("NEW_histogram_dependencies_aggregate_ja.png", plot=hist.12.all.ja, device="png", dpi = 300)
hist.12.all.ja

```

```{r hist_bychannel_ja, include=TRUE, echo=FALSE}

hist.12.channel.ja <- ggplot(data=df.all.ja.12 %>% filter(channel != "FischersCorrected"), aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    facet_wrap(.~channel) + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths by Channel For Length=12, Japanese") +
  theme(legend.position="bottom")

ggsave("NEW_histogram_dependencies_channel_ja.png", plot=hist.12.channel.ja, device="png", dpi = 300)
hist.12.channel.ja

```

```{r aggregate_hist_ru, include=TRUE, echo=FALSE}

hist.12.all.ru <- ggplot(data=df.all.ru.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths For Sentences of Length 12, Russian") + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    theme(legend.position="bottom")

ggsave("NEW_histogram_dependencies_aggregate_ru.png", plot=hist.12.all.ru, device="png", dpi = 300)
hist.12.all.ru

```

```{r hist_bychannel_ru, include=TRUE, echo=FALSE}

hist.12.channel.ru <- ggplot(data=df.all.ru.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity") + 
    facet_wrap(.~channel) + 
    scale_fill_manual(values = c("#5B675D", "#60C7AA", "#A1C439"),
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill")) +
    labs(x="Dependency Length", y="Frequency", title="Distribution of Dependency Lengths by Channel For Lenth=12, Russian") +
  theme(legend.position="bottom")

ggsave("NEW_histogram_dependencies_channel_ru.png", plot=hist.12.channel.ru, device="png", dpi = 300)
hist.12.channel.ru

```

```{r}
all.dependencies.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=baseline)) + 
    stat_bin_hex(data=df.all.ja.observed.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_smooth(aes(group=baseline), se = FALSE, method = "gam", formula = y ~ s(log(x)), show.legend = FALSE) + 
    labs(title="", x="", y="", color="") + 
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed"))
  
# Plot by channel
dep.by.channel.g <- ggplot(df.all.ja.avg, aes(y=avg_length, x=total_length, color=baseline, group=channel)) + 
    stat_bin_hex(data=df.all.ja.observed.avg, bins=20, show.legend=FALSE, inherit.aes=FALSE, 
                 aes(y=dep_length, x=total_length, fill=..density..)) +
    scale_fill_gradientn(colours=c("white","black")) +
    geom_smooth(aes(group=baseline), se = FALSE, method = "gam", formula = y ~ s(log(x)), show.legend=FALSE) + 
    labs(title="", x="", y="", color="") + 
    theme(legend.position="top") +
    scale_color_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], labels=c("Random", "Optimal", "Observed")) +
    facet_wrap(.~channel)
  
g <- grid.arrange(all.dependencies.g, dep.by.channel.g, ncol=2, left="Total Dependency Length", bottom="Sentence Length", widths=unit(c(3,6), c("in", "in")))

```

```{r}
hist.12.channel.g <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity", show.legend=FALSE) + 
    facet_wrap(.~channel) + 
    labs(x="", y="", title="",color="", fill="") + 
    theme(legend.position="top") +
    scale_fill_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], 
                      labels = c("Random", "Optimal", "Observed"), aesthetics = c("colour", "fill"))

hist.12.all.g <- ggplot(data=df.all.ja.12, aes(y=frequency, x=dep_length, fill=baseline, color=baseline)) + 
    geom_histogram(aes(y=..density.., fill=baseline), alpha=0.5, binwidth=1, position="identity", show.legend=FALSE) + 
    labs(x="", y="", title="",color="", fill="") + 
    theme(legend.position="bottom") +
    scale_fill_manual(values = ghibli_palette("PonyoMedium")[c(3,4,6)], 
                      labels = c("Rand", "Opt", "Obs"), aesthetics = c("colour", "fill"))
g2 <- grid.arrange(hist.12.all.g, hist.12.channel.g, ncol=2, left="Frequency", bottom="Total Dependency Length", widths=unit(c(3,6), c("in", "in")))
```

```{r new_linear_models_setup, include=FALSE}

df.all.fischerscorrected.lm <- df.all.ja %>% filter(channel == "FischersCorrected") 
df.all.fischersauto.lm      <- df.all.ja %>% filter(channel == "FischersAuto") 
df.all.fischers.lm          <- df.all.ja %>% filter(channel == "FischersAuto" | channel == "FischersCorrected") 
df.all.ja.lm                <- df.all.ja %>% filter(channel != "FischersCorrected") 

df.ja.r <- df.all.ja.lm %>% filter(baseline == "Random")   %>% select(channel, dep_length, sent_len_sq)
df.ja.m <- df.all.ja.lm %>% filter(baseline == "Optimal")  %>% select(channel, dep_length, sent_len_sq)
df.ja.o <- df.all.ja.lm %>% filter(baseline == "Observed") %>% select(channel, dep_length, sent_len_sq)

df.ru.r <- df.all.ru %>% filter(baseline == "Random")   %>% select(channel, dep_length, sent_len_sq)
df.ru.m <- df.all.ru %>% filter(baseline == "Optimal")  %>% select(channel, dep_length, sent_len_sq)
df.ru.o <- df.all.ru %>% filter(baseline == "Observed") %>% select(channel, dep_length, sent_len_sq)

df.fischerscorrected.r <- df.all.fischerscorrected.lm %>% filter(baseline == "Random")   %>% select(dep_length, sent_len_sq)
df.fischerscorrected.m <- df.all.fischerscorrected.lm %>% filter(baseline == "Optimal")  %>% select(dep_length, sent_len_sq)
df.fischerscorrected.o <- df.all.fischerscorrected.lm %>% filter(baseline == "Observed") %>% select(dep_length, sent_len_sq)

df.fischersauto.r <- df.all.fischersauto.lm %>% filter(baseline == "Random")   %>% select(dep_length, sent_len_sq)
df.fischersauto.m <- df.all.fischersauto.lm %>% filter(baseline == "Optimal")  %>% select(dep_length, sent_len_sq)
df.fischersauto.o <- df.all.fischersauto.lm %>% filter(baseline == "Observed") %>% select(dep_length, sent_len_sq)

df.fischers.r <- df.all.fischers.lm %>% filter(baseline == "Random")   %>% select(channel, dep_length, sent_len_sq)
df.fischers.m <- df.all.fischers.lm %>% filter(baseline == "Optimal")  %>% select(channel, dep_length, sent_len_sq)
df.fischers.o <- df.all.fischers.lm %>% filter(baseline == "Observed") %>% select(channel, dep_length, sent_len_sq)

```

```{r gamm}
df.all.gam <- df.all %>% filter(baseline == "Observed")
all.gam <- gam(dep_length ~ language + s(total_length, bs="cr") + s(total_length, by=language, bs="cr"), data=df.all.gam, method="ML")
```
```{r gam_plots}
plot_smooth(all.gam, view="total_length", plot_all="language", rug=F)
plot_diff(all.gam, view="total_length", comp=list(word=c("Russian","Japanese")))
```

```{r lm_ja_random}
dependency.model.ja.r <- lm(dep_length ~ sent_len_sq, data=(df.ja.r %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ja.r)
```

```{r lm_fischers_random}
dependency.model.fischerscorrected.r <- lm(dep_length ~ sent_len_sq, data=(df.fischerscorrected.r %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischerscorrected.r)

dependency.model.fischersauto.r <- lm(dep_length ~ sent_len_sq, data=(df.fischersauto.r %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischersauto.r)

dependency.model.fischers.r <- lm(dep_length ~ sent_len_sq*channel, data=(df.fischers.r %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischers.r)
```

```{r lmer_fischers_comp_random}
dependency.model.fischers.r <- lmer(dep_length ~ sent_len_sq*channel + (1|channel), data=(df.fischers.r %>% filter(sent_len_sq <= 1600)))
dependency.model.fischers.r.noint <- lmer(dep_length ~ sent_len_sq + channel + (1|channel), data=(df.fischers.r %>% filter(sent_len_sq <= 1600)))

summary(dependency.model.fischers.r)
summary(dependency.model.fischers.r.noint)

anova(dependency.model.fischers.r, dependency.model.fischers.r.noint)
```

```{r lm_ru_random}
dependency.model.ru.r <- lm(dep_length ~ sent_len_sq, data=(df.ru.r %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ru.r)
```

```{r lm_ja_observed}
dependency.model.ja.o <- lm(dep_length ~ sent_len_sq, data=(df.ja.o %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ja.o)
```

```{r lm_fischers_observed}
dependency.model.fischerscorrected.o <- lm(dep_length ~ sent_len_sq, data=(df.fischerscorrected.o %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischerscorrected.o)

dependency.model.fischersauto.o <- lm(dep_length ~ sent_len_sq, data=(df.fischersauto.o %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischersauto.o)
```

```{r lmer_comp_fischers_observed}
dependency.model.fischers.o <- lmer(dep_length ~ sent_len_sq*channel + (1|channel), data=(df.fischers.o %>% filter(sent_len_sq <= 1600)))
dependency.model.fischers.o.noint <- lmer(dep_length ~ sent_len_sq + channel + (1|channel), data=(df.fischers.o %>% filter(sent_len_sq <= 1600)))

summary(dependency.model.fischers.o)
summary(dependency.model.fischers.o.noint)

anova(dependency.model.fischers.o, dependency.model.fischers.o.noint)
```

```{r lm_ru_observed}
dependency.model.ru.o <- lm(dep_length ~ sent_len_sq, data=(df.ru.o %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ru.o)
```

```{r lm_ja_optimal}
dependency.model.ja.m <- lm(dep_length ~ sent_len_sq, data=(df.ja.m %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ja.m)
```

```{r lm_fischers_optimal}
dependency.model.fischerscorrected.m <- lm(dep_length ~ sent_len_sq, data=(df.fischerscorrected.m %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischerscorrected.m)

dependency.model.fischersauto.m <- lm(dep_length ~ sent_len_sq, data=(df.fischersauto.m %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.fischersauto.m)
```

```{r lmer_comp_fischers_optimal}
dependency.model.fischers.m <- lmer(dep_length ~ sent_len_sq*channel + (1|channel), data=(df.fischers.m %>% filter(sent_len_sq <= 1600)))
dependency.model.fischers.m.noint <- lmer(dep_length ~ sent_len_sq + channel + (1|channel), data=(df.fischers.m %>% filter(sent_len_sq <= 1600)))

summary(dependency.model.fischers.m)
summary(dependency.model.fischers.m.noint)

anova(dependency.model.fischers.m, dependency.model.fischers.m.noint)
```

```{r lm_ru_optimal}
dependency.model.ru.m <- lm(dep_length ~ sent_len_sq, data=(df.ru.m %>% filter(sent_len_sq <= 1600)))
summary(dependency.model.ru.m)
```

```{r}
df.ja.predicted.r <- ggpredict(dependency.model.r, terms = c("sent_len_sq"))
df.ja.predicted.o <- ggpredict(dependency.model.o, terms = c("sent_len_sq"))
df.ja.predicted.m <- ggpredict(dependency.model.m, terms = c("sent_len_sq"))

ggplot(df.ja.predicted, aes(x=sqrt(x), y=predicted, group=group, color=group)) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)
```

```{r old_lmer_models}
# sent  l       y   l^2   m   r
# 1     10      30  100   0   0 
# 1     10      20  100   1   0 
# 1     10      40  100   0   1 

# Structural model: y_i = β_0 + S_0 + β_1l_2^s + (β_2 + S_2)r_i + β_3r_il_2^s + e_i
# β_0 = slope
# β_1, β_2,  β_3 = fixed effects
# S_0, S_2 = random effects (intercept, slope) by sentence
# r_i = ind. var. for random
# m_i = ind. var. for optimal

# Compute models
dependency.model.or <- lmer(dep_length ~ sent_len_sq*r + sent_len_sq*o + (1|sentence_uid), data=(df.ja.auto %>% filter(channel == "Yuka")))
summary(dependency.model.or)

dependency.model.mr <- lmer(dep_length ~ sent_len_sq*r + sent_len_sq*m + (1|sentence_uid), data=(df.ja.auto %>% filter(channel == "Yuka")))
summary(dependency.model.mr)

dependency.model.o <- lmer(dep_length ~ sent_len_sq*o + (1+sent_len_sq|sentence_uid), data=temp, REML=F)
summary(dependency.model.o)

#dependency.model.nob3 <- lmer(dep_length ~ sent_len_sq + r + (1+r||(video_id:sentence_id)), data=temp)

# Random = 0, obs = 1
#dependency.model.b3 <- lmer(dep_length ~ sent_len_sq + o:sent_len_sq + o + (1+o||(video_id:sentence_id)), data=temp)
```

```{r, include=TRUE}
# Compare models
anova(dependency.model.b3,dependency.model.nob3)
```